### ISSUE TITLE
Requires user to install additional libs, but no doc about that, and no auto install script either. 

### ISSUE THREAD

**Issue by atljoseph** [AndreasArvidsson/andreas-talon#15]
Talon version. 
On the beta version on one computer and public on another. In transition to beta 100%. Both latest releases. 

Why I landed here. 
Came here originally trying to figure out why the switch wired controller dpad keys weren’t registering at all (**still not solved… recognizes everything but dpad**), but ended up learning about wiring up the parrot cluck for wake, and a couple other things. 

How to proceed past issue?
So, When I started talon with this config, it auto-installed torch (would like to understand why it is needed, but minor). It also relies on Ollama and google translate libs, **but those aren’t automatically installed.** So I’m not sure if I should try to install those or just revert to community config. 

How to approach this repo?
Lastly, How should I be using this repo? Not entirely sure if this is meant to be a drop in alternative to the community config or if this is meant to serve as an example about how the community config can be enhanced. 

Thank you!

**Comment by AndreasArvidsson** [comment]
Torch is installed automatically because it's needed by the parrot integration. ollama and other third party dependencies are my own and not something Talon knows about. 

In most of these files I leave installation instructions in the file itself. eg:
https://github.com/AndreasArvidsson/andreas-talon/blob/56426e2ad227e652a3ea9d54f3462112f492b5ac/plugins/llm/ollama.py#L1-L2

This repository is not really meant for public consumption. It's just my personal repository of user scripts. 

Even though I think I have a lot off improvements compared to community and I try to add stuff to community when I have some spare time. This is not really made to be a community replacement. For example I basically don't have any settings and instead the code just does what I think it should do without the ability to change behavior with settings. Compare this to community where we have a lot of settings and tags to help users to easily change behavior.

**Comment by atljoseph** [comment]
am ending up going piece meal, mostly based on community. This is a good resource though! And search.talonvoice.com! Thanks again for what you do! Closing this issue.

**Comment by AndreasArvidsson** [comment]
Basing your scripts on community and then copying from other repository sounds like a good plan.
Glad to help! :)
